# Generated by Django 4.1.1 on 2022-09-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('params', models.JSONField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_on', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'crawler_manager',
                'managed': False,
            },
        ),
    ]
